before_install:
    - sudo ./scripts/texlive_install.sh
    - PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH; export PATH
language: node_js
node_js: 
    - "lts/*"
    - "node"

addons:
  apt:
    packages:
    - rabbitmq-server 
    
install:
    - npm install -g codecov
    - npm ci
    - grunt doc

after_success:
    - npm run report-coverage
    - codecov
    - grunt clean

directories:
    - "node_modules"