before_install:
    - sudo ./scripts/texlive_install.sh
    - PATH=/usr/local/texlive/2019/bin/x86_64-linux:$PATH; export PATH
language: node_js
node_js: 
    - "lts/*"
    - "node"

install:
    - npm ci
    - grunt doc

after_success:
    - grunt clean

directories:
    - "node_modules"